### ISSUE TITLE
A bunch of small style improvements

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#36]
As a user I want the following style improvements so that my experience is more awesome. 

- The "Welcome back, [Name]" section of the SignUpForm that you see after signing it and reloading the homepage, should use the same paragraph font use elsewhere on the site. 
- The "click here" text link in referred to the in previous bullet point should be the same red as our buttons 
- Share icons in SignUpShare should have cursor:pointer on hover
- When you hover over the non-active Tab titles in the TheThreeDays component, the text moves slightly - could we make this not happen?
- Could we make the hamburger icon in the homePageNav and getInvolvedNav white, rather than grey?

**Comment by M4rk9696** [comment]
Working on it

**Comment by M4rk9696** [comment]
- [x] The "Welcome back, [Name]" section of the SignUpForm that you see after signing it and reloading the homepage, should use the same paragraph font use elsewhere on the site.
- [x] The "click here" text link in referred to the in previous bullet point should be the same red as our buttons
- [x] Share icons in SignUpShare should have cursor:pointer on hover
- [ ] When you hover over the non-active Tab titles in the TheThreeDays component, the text moves slightly - could we make this not happen?
- [x] Could we make the hamburger icon in the homePageNav and getInvolvedNav white, rather than grey?
- [x] Space in italic text in Join the Action
